/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace Voting {
      
    export type CandidateStruct = {name: string, voteCount: BigNumberish}

    export type CandidateStructOutput = [name: string, voteCount: bigint] & {name: string, voteCount: bigint }
  
    }

  export interface VotingInterface extends Interface {
    getFunction(nameOrSignature: "candidates" | "getCandidates" | "hasVoted" | "owner" | "vote"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Voted"): EventFragment;

    encodeFunctionData(functionFragment: 'candidates', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCandidates', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'candidates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCandidates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
  }

  
    export namespace VotedEvent {
      export type InputTuple = [voter: AddressLike, candidateIndex: BigNumberish];
      export type OutputTuple = [voter: string, candidateIndex: bigint];
      export interface OutputObject {voter: string, candidateIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Voting extends BaseContract {
    
    connect(runner?: ContractRunner | null): Voting;
    waitForDeployment(): Promise<this>;

    interface: VotingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    candidates: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint] & {name: string, voteCount: bigint }],
      'view'
    >
    

    
    getCandidates: TypedContractMethod<
      [],
      [Voting.CandidateStructOutput[]],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    vote: TypedContractMethod<
      [candidateIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'candidates'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint] & {name: string, voteCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getCandidates'): TypedContractMethod<
      [],
      [Voting.CandidateStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [candidateIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Voted'): TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;

    filters: {
      
      'Voted(address,uint256)': TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
      Voted: TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
    
    };
  }